name: Cloudflare Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cloudflare-test:
    name: Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm ci

      - name: Create Wrangler Config
        run: |
          cat > wrangler.toml << 'EOF'
          name = "ohimg-test"
          main = "tests/worker.test.js"
          compatibility_date = "2024-01-01"
          EOF

      - name: Run Worker Tests
        run: |
          npx wrangler deploy --dry-run tests/worker.test.js
          npm run test:cloudflare
