name: Browser Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  browser-test:
    name: Playwright Browser Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Create browser test
        run: |
          mkdir -p tests/environments
          cat > tests/environments/browser.test.ts << 'EOF'
          import { test, expect } from '@playwright/test';

          test('OhImg works in browser environment', async ({ page }) => {
            await page.goto('about:blank');
            
            const result = await page.evaluate(async () => {
              const { OhImg } = await import('../../src/index');
              
              const ohimg = new OhImg({
                apiKey: 'og_live_test',
                webhookSecret: 'og_whsec_test'
              });
              
              return ohimg.getImageUrl({
                path: '/test',
                domain: 'https://example.com'
              });
            });
            
            expect(typeof result).toBe('string');
            expect(result.startsWith('https://og.ohimg.dev')).toBeTruthy();
            
            // Test Web Crypto API
            const hasWebCrypto = await page.evaluate(() => {
              return typeof crypto !== 'undefined' && typeof crypto.subtle !== 'undefined';
            });
            
            expect(hasWebCrypto).toBe(true);
          });
          EOF

      - name: Create Playwright config
        run: |
          cat > playwright.config.ts << 'EOF'
          import { PlaywrightTestConfig } from '@playwright/test';

          const config: PlaywrightTestConfig = {
            testDir: './tests/environments',
            testMatch: 'browser.test.ts',
            use: {
              browserName: 'chromium',
            },
          };
          export default config;
          EOF

      - run: npx playwright test
