name: Deno Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deno-test:
    name: Deno
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno Tests
        run: deno test tests/deno.test.js --allow-net
